# Generated by Django 5.1.15 on 2026-06-26 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('auth', '认证'), ('achievement', '成果'), ('review', '审核'), ('publicity', '公示'), ('statistics', '统计'), ('export', '导出'), ('system', '系统')], max_length=20, verbose_name='模块')),
                ('action', models.CharField(choices=[('login', '登录'), ('create', '新增'), ('update', '修改'), ('delete', '删除'), ('approve', '通过'), ('return', '退回'), ('reject', '驳回'), ('publish', '发布'), ('close', '结束'), ('export', '导出')], max_length=20, verbose_name='动作')),
                ('detail', models.TextField(blank=True, default='', verbose_name='操作说明')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'created_at'], name='operation_l_module_f1a84a_idx')],
            },
        ),
    ]
