# Generated by Django 5.1.15 on 2026-06-22 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('evaluations', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='成果名称')),
                ('achievement_date', models.DateField(blank=True, null=True, verbose_name='获得日期')),
                ('level', models.CharField(blank=True, default='', max_length=20, verbose_name='成果等级')),
                ('description', models.TextField(blank=True, default='', verbose_name='成果说明')),
                ('attachment', models.FileField(blank=True, upload_to='uploads/%Y/%m/', verbose_name='附件')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='认定分数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('reviewing', '测评小组审核中'), ('counselor_reviewing', '待辅导员终审'), ('approved', '已通过'), ('rejected', '已驳回')], default='draft', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='evaluations.evaluationbatch', verbose_name='测评批次')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='achievements.achievementcategory', verbose_name='成果分类')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='organizations.class', verbose_name='班级')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '成果',
                'verbose_name_plural': '成果',
                'db_table': 'achievements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student'], name='achievement_student_535b23_idx'), models.Index(fields=['batch'], name='achievement_batch_i_7a283b_idx'), models.Index(fields=['status'], name='achievement_status_c5c2ae_idx'), models.Index(fields=['category'], name='achievement_categor_b833b2_idx'), models.Index(fields=['class_obj', 'status'], name='achievement_class_o_489659_idx'), models.Index(fields=['batch', 'class_obj'], name='achievement_batch_i_2cc07b_idx')],
            },
        ),
    ]
