# Generated by Django 5.1.15 on 2026-06-22 11:42

import apps.achievements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='attachment',
            field=models.FileField(blank=True, upload_to=apps.achievements.models._rename_attachment, verbose_name='附件'),
        ),
    ]
