# Generated by Django 5.1.15 on 2026-06-22 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_alter_achievement_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewer_name', models.CharField(default='', max_length=50, verbose_name='审核人姓名（快照）')),
                ('review_stage', models.CharField(choices=[('evaluator', '测评小组'), ('counselor', '辅导员')], max_length=20, verbose_name='审核阶段')),
                ('action', models.CharField(choices=[('approve', '通过'), ('reject', '驳回'), ('return', '退回')], max_length=20, verbose_name='动作')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='认定分数')),
                ('comment', models.CharField(blank=True, default='', max_length=500, verbose_name='审核意见')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='achievements.achievement', verbose_name='成果')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
                'db_table': 'audit_records',
                'ordering': ['created_at'],
            },
        ),
    ]
