# Generated by Django 5.1.15 on 2026-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_no',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='工号'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_no',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='学号'),
        ),
    ]
