# Generated by Django 5.1.15 on 2026-06-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='批次名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='批次说明')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '测评批次',
                'verbose_name_plural': '测评批次',
                'db_table': 'evaluation_batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
