# Generated by Django 5.1.15 on 2026-06-26 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='公示标题')),
                ('start_time', models.DateTimeField(verbose_name='公示开始时间')),
                ('end_time', models.DateTimeField(verbose_name='公示结束时间')),
                ('status', models.IntegerField(choices=[(0, '草稿'), (1, '公示中'), (2, '已结束')], db_index=True, default=0, verbose_name='状态')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_notices', to='evaluations.evaluationbatch', verbose_name='测评批次')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_notices', to='organizations.class', verbose_name='班级')),
            ],
            options={
                'verbose_name': '公示',
                'verbose_name_plural': '公示',
                'db_table': 'public_notices',
                'ordering': ['-created_at'],
            },
        ),
    ]
