# Generated by Django 5.1.15 on 2026-06-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
        ('organizations', '0001_initial'),
        ('publicity', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='publicnotice',
            constraint=models.UniqueConstraint(fields=('batch', 'class_obj'), name='unique_batch_class_notice'),
        ),
    ]
