# Generated by Django 5.1.15 on 2026-06-26 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='总得分')),
                ('ranking', models.PositiveIntegerField(default=0, verbose_name='班级排名（0=未排名）')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_summaries', to='evaluations.evaluationbatch', verbose_name='测评批次')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_summaries', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '成绩汇总',
                'verbose_name_plural': '成绩汇总',
                'db_table': 'score_summaries',
                'ordering': ['batch', '-total_score'],
                'indexes': [models.Index(fields=['student', 'batch'], name='score_summa_student_e7b577_idx'), models.Index(fields=['batch', 'ranking'], name='score_summa_batch_i_6b4219_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'batch'), name='unique_student_batch_score')],
            },
        ),
    ]
